version: '3'
services:
  arangodb:
    image: arangodb:3.8
    environment:
      ARANGO_ROOT_PASSWORD: "${ARANGODB_PASSWORD}"
    volumes:
      - "arangodb-data-store:/var/lib/arangodb3"
      - "arangodb-extension-store:/var/lib/arangodb3-apps"
    ports:
      - "${ARANGODB_PORT}:8529"

volumes:
  arangodb-data-store:
    driver: local
  arangodb-extension-store:
    driver: local
